apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
stringData:
  symmetricKey: {{ required "Base64 encoded symmetric key for Piraeus authentication" .Values.symmetricKey }}
  hostname: {{ required "Hostname of Piraeus connection" .Values.hostname }}
  location: {{ required "Location of Web Monitor connection" .Values.location }}
  storageConnectionString: {{ required "Azure Blob Storage connection string to read-only LUSS table for VRTU" .Values.storageConnectionString }}
  tableName: {{ required "Location of Web Monitor connection" .Values.tableName }}
  instrumentationKey: {{ required "App Insights instrumentation key." .Values.instrumentationKey }}
  logLevel: {{ required "Log Level of VRTU" .Values.logLevel }}
  tenantId: {{ required "Log Level of VRTU" .Values.tenantId }}
  clientId: {{ required "Log Level of VRTU" .Values.clientId }}
  domain: {{ required "Log Level of VRTU" .Values.domain }}