apiVersion: v1
kind: Service
metadata:  
  name:  monitor
  labels:
    app:  monitor
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component:  monitor
spec:
  type: ClusterIP
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  
  selector:
    app:  monitor
    release: {{ .Release.Name }}
    component:  monitor
status:
  loadBalancer: {}