FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS build-env
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS runtime
WORKDIR /app


ENTRYPOINT ["dotnet", "IoTEdge.VirtualRtu.WebMonitor.dll"]
COPY . /app