FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS build-env
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app
EXPOSE 8080

ENTRYPOINT ["dotnet", "VirtualRtu.WebMonitor.dll"]
COPY . /app