apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
stringData:
  dataConnectionString: {{ required "A value is required for dataConnectionString" .Values.dataConnectionString }}  
  instrumentationKey: {{ required "A value is required for instrumentation key" .Values.instrumentationKey }}  
  logLevel: {{ required "A value is required for log level" .Values.logLevel }}  
  