apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -c
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: piraeus-silo
  name: piraeus-silo
spec:
  type: ClusterIP
  ports:
  - name: "11111"
    port: 11111
    targetPort: 11111
  - name: "30000"
    port: 30000
    targetPort: 30000
  selector:
    io.kompose.service: piraeus-silo
status:
  loadBalancer: {}
