apiVersion: v1
kind: Service
metadata:  
  name: websocket
  labels:
    app: websocket
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: websocket
spec:
  type: ClusterIP
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  
  selector:
    app: websocket
    release: {{ .Release.Name }}
    component: websocket
status:
  loadBalancer: {}

