apiVersion: v1
description: A Helm chart for VRTU Monitoring
name: virtualrtu-webmonitor
version: 0.0.3
icon: https://avatars2.githubusercontent.com/u/25301165?s=400&v=4
appVersion: 0.0.3
keywords:
  - virtual rtu
  - vrtu
home: https://github.com/skunklab/virtualrtu
sources:
  - https://github.com/skunklab/virtualrtu
maintainers:
  - name: Matt Long
    email: malong@microsoft.com
tillerVersion: ">=2.7.0-rc1"